# Generated by Django 6.0.1 on 2026-01-11 18:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desbravador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('anotacoes_gerais', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(choices=[('DIR', 'Diretor (Acesso Total)'), ('VICE', 'Vice-Diretor (Acesso Total)'), ('CAP', 'Capelão (Acesso Supremo/Visualização)'), ('CONS', 'Conselheiro'), ('INST', 'Instrutor'), ('SEC', 'Secretário')], default='CONS', max_length=4)),
                ('status_aprovado', models.BooleanField(default=False, verbose_name='Acesso Aprovado?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('unidade_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conselheiros', to='core.unidade')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('biblia', models.IntegerField(choices=[(0, '0 Pontos - Não trouxe/Não fez'), (5, '5 Pontos - Incompleto/Parcial'), (10, '10 Pontos - Completo')], default=0, verbose_name='Bíblia')),
                ('uniforme', models.IntegerField(choices=[(0, '0 Pontos - Não trouxe/Não fez'), (5, '5 Pontos - Incompleto/Parcial'), (10, '10 Pontos - Completo')], default=0, verbose_name='Uniforme')),
                ('lenco', models.IntegerField(choices=[(0, '0 Pontos - Não trouxe/Não fez'), (5, '5 Pontos - Incompleto/Parcial'), (10, '10 Pontos - Completo')], default=0, verbose_name='Lenço')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('desbravador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.desbravador')),
            ],
            options={
                'verbose_name': 'Avaliação Semanal',
                'verbose_name_plural': 'Avaliações Semanais',
            },
        ),
        migrations.CreateModel(
            name='AnotacaoDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('visivel', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('desbravador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desbravador')),
            ],
        ),
        migrations.CreateModel(
            name='PontoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=100)),
                ('pontos', models.IntegerField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('desbravador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_extras', to='core.desbravador')),
            ],
        ),
        migrations.AddField(
            model_name='desbravador',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='core.unidade'),
        ),
    ]
