# Generated by Django 6.0.1 on 2026-01-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacaodisciplinar',
            options={'verbose_name': 'Anotação Disciplinar', 'verbose_name_plural': 'Anotações Disciplinares'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('DIR', 'Diretor (Acesso Total)'), ('VICE', 'Vice-Diretor (Acesso Total)'), ('CAP', 'Capelão (Acesso Supremo)'), ('CONS', 'Conselheiro'), ('INST', 'Instrutor'), ('SEC', 'Secretário')], default='CONS', max_length=4),
        ),
    ]
