# Generated by Django 6.0.1 on 2026-01-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_anotacaodisciplinar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='clube_visivel',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Clube Visível (Uniforme na Igreja)'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='escola_sabatina',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Escola Sabatina'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='estudo_biblico',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Estudo Bíblico'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='fanfarra',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Ensaio da Fanfarra'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='fazer_ideal',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Fazer o Ideal (Voto/Lei)'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='itens_cartao',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Itens do Cartão/Classe'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='orar',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Orar'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='ordem_unida',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Ensaio de Ordem Unida'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='participacao',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Participação Ativa'),
        ),
        migrations.AddField(
            model_name='avaliacaosemanal',
            name='pequeno_grupo',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Pequeno Grupo'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='biblia',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Bíblia'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='lenco',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Lenço'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='uniforme',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (5, '5 Pontos - Incompleto'), (10, '10 Pontos - Completo')], default=0, verbose_name='Uniforme Completo'),
        ),
    ]
