# Generated by Django 6.0.1 on 2026-01-27 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliacaosemanal_clube_visivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacaodisciplinar',
            options={},
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.unidade')),
            ],
        ),
    ]
