# Generated by Django 6.0.1 on 2026-02-02 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_anotacaodisciplinar_options_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('AM', 'Amigo'), ('AP', 'Companheiro'), ('PE', 'Pesquisador'), ('PI', 'Pioneiro'), ('EX', 'Excursionista'), ('GU', 'Guia')], max_length=2, unique=True)),
                ('cor_referencia', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('AD', 'ADRA'), ('AA', 'Artes'), ('AV', 'Agro'), ('AM', 'Missionárias'), ('AR', 'Recreativas'), ('CS', 'Saúde'), ('EN', 'Ecologia'), ('HM', 'Domésticas'), ('OT', 'Outros')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='pontoextra',
            name='pontos',
            field=models.IntegerField(help_text='Use negativo para tirar pontos (Ex: -10)'),
        ),
        migrations.CreateModel(
            name='ConquistaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(default=django.utils.timezone.now)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classe')),
                ('desbravador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='core.desbravador')),
                ('instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.especialidade')),
            ],
        ),
    ]
