# Generated by Django 6.0.1 on 2026-02-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classe_especialidade_alter_pontoextra_pontos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.unidade'),
        ),
    ]
