# Generated by Django 6.0.1 on 2026-02-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_evento_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_diretoria',
            field=models.BooleanField(default=False, verbose_name='É Diretoria?'),
        ),
    ]
