# Generated by Django 6.0.1 on 2026-02-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_is_diretoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='cor',
            field=models.CharField(choices=[('bg-primary', 'Azul (Padrão)'), ('bg-danger', 'Vermelho'), ('bg-success', 'Verde'), ('bg-warning text-dark', 'Amarelo'), ('bg-info text-dark', 'Ciano/Azul Claro'), ('bg-dark', 'Preto/Cinza Escuro'), ('bg-rosa', 'Rosa (Safira)'), ('bg-roxo', 'Roxo'), ('bg-laranja', 'Laranja')], default='bg-primary', max_length=30, verbose_name='Cor da Unidade'),
        ),
    ]
