# Generated by Django 6.0.1 on 2026-04-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_unidade_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='biblia',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Bíblia'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='clube_visivel',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Clube Visível (Uniforme na Igreja)'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='escola_sabatina',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Escola Sabatina'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='estudo_biblico',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Estudo Bíblico'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='fazer_ideal',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Fazer o Ideal (Voto/Lei)'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='lenco',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Lenço'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='orar',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Orar'),
        ),
        migrations.AlterField(
            model_name='avaliacaosemanal',
            name='pequeno_grupo',
            field=models.IntegerField(choices=[(0, '0 Pontos - Não fez/Não foi'), (10, '10 Pontos - Completo')], default=0, verbose_name='Pequeno Grupo'),
        ),
    ]
