# Generated by Django 6.0.1 on 2026-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_avaliacaosemanal_biblia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desbravador',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado pela Diretoria'),
        ),
    ]
