# Generated by Django 6.0.1 on 2026-05-17 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_desbravador_aprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Alerta')),
                ('mensagem', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Disparado em')),
                ('destinatarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Enviar para os Usuários')),
            ],
            options={
                'verbose_name': 'Notificação Manual',
                'verbose_name_plural': 'Notificações Manuais',
            },
        ),
    ]
