# Generated by Django 6.0.1 on 2026-05-23 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notificacaomanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoInApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_inapp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso do Sistema',
                'verbose_name_plural': 'Avisos do Sistema',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
